# https://kit.svelte.dev/docs/adapter-static#github-pages
name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: "main"

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: build
        env:
          BASE_URL: "/wildfires-protomaps"
        run: |
          npm run build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: "dist/"

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
